import { test, expect } from '@playwright/test'

test('compares all days and updates the trip budget and selected route', async ({ page }) => {
  await page.goto('/#/dubai/plan?idea=minmax')
  await page.getByRole('button', { name: 'Применить minmax на все пять дней', exact: true }).click()
  const overview = page.getByRole('region', { name: 'Обзор поездки', exact: true })
  await expect(overview).toContainText('Семья 1 · 4 взрослых')
  await expect(overview.getByLabel('Бюджет поездки')).toContainText('₽')
  const first = await overview.getByLabel('Бюджет поездки').innerText()
  await page.getByLabel('Чьи расходы показать', { exact: true }).selectOption('both')
  await expect(overview).toContainText('Обе семьи · 6 человек')
  await expect(overview.getByLabel('Бюджет поездки')).not.toHaveText(first)
  await overview.locator('summary').click()
  await expect(overview.locator('.trip-day-card')).toHaveCount(5)
  await expect(overview.locator('.trip-day-card img')).toHaveCount(5)
  await expect(overview.locator('.trip-day-status.tight')).toHaveCount(0)
  await overview
    .getByRole('button', { name: 'Открыть маршрут на 8 октября 2026 г.', exact: true })
    .click()
  await expect(page.locator('.plan-stops:visible')).toContainText('Сад цветов Miracle Garden')
  await expect(page.getByRole('region', { name: 'День 3', exact: true })).toBeFocused()
  await page
    .getByRole('region', { name: 'День 3', exact: true })
    .getByLabel('Вернуться в отель до', { exact: true })
    .fill('13:00')
  await expect(overview).toContainText('требуют правки: 1')
  await expect(overview.locator('.trip-day-status.tight')).toHaveCount(1)
  await expect(overview.locator('.trip-day-card').nth(2)).toContainText('Вернуться до 13:00')
  await page.setViewportSize({ width: 360, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.reload()
  await expect(overview).toContainText('требуют правки: 1')
})

test('opens an empty day without changing a shared plan', async ({ page }) => {
  await page.goto('/#/dubai/plan')
  const overview = page.getByRole('region', { name: 'Обзор поездки', exact: true })
  await expect(overview.getByLabel('Бюджет поездки')).toContainText('0 AED')
  await overview.locator('summary').click()
  await overview
    .getByRole('button', { name: 'Открыть маршрут на 9 октября 2026 г.', exact: true })
    .click()
  await expect(page.locator('.plan-picker h2')).toContainText('9 октября')
  await page.getByRole('button', { name: 'Поделиться', exact: true }).click()
  const link = await page.getByLabel('Ссылка на план', { exact: true }).inputValue()
  await page.goto(link)
  await page.reload()
  await overview.locator('summary').click()
  await overview
    .getByRole('button', { name: 'Открыть маршрут на 10 октября 2026 г.', exact: true })
    .click()
  await expect(page.getByRole('region', { name: 'День 5', exact: true })).toBeVisible()
  await expect(page.locator('.plan-picker')).toHaveCount(0)
  await page.getByRole('link', { name: 'Мой план', exact: true }).click()
  await expect(page.locator('.plan-stop:visible')).toHaveCount(0)
})
