import { test, expect } from '@playwright/test'

test('keeps a personal plan and opens a shared snapshot', async ({ page }) => {
  await page.goto('/#/dubai/place/burj-khalifa')
  await page
    .locator('.place-story')
    .getByRole('button', { name: 'В план: Бурдж-Халифа', exact: true })
    .click()
  await page.getByRole('link', { name: 'План', exact: true }).click()
  await expect(page.locator('.plan-stop:visible')).toHaveCount(1)
  await expect(page.locator('.hotel-base')).toContainText('JA Palm Tree Court')
  await page.getByLabel('День: Бурдж-Халифа').selectOption('2026-10-07')
  await page.getByRole('button', { name: /День 2/ }).click()
  await expect(page.locator('.plan-stop:visible')).toHaveCount(1)
  await page.reload()
  await page.getByRole('button', { name: /День 2/ }).click()
  await expect(page.locator('.plan-stop:visible')).toHaveCount(1)
  await page.getByRole('button', { name: 'Поделиться', exact: true }).click()
  const url = await page.getByLabel('Ссылка на план').inputValue()
  await page.goto(url)
  await expect(page.getByText('Копия плана по ссылке')).toBeVisible()
  await expect(page.locator('.plan-day-tab.active')).toContainText('День 2')
  await expect(page.locator('.plan-stop:visible')).toHaveCount(1)
  await expect(page.getByRole('button', { name: /Убрать из плана/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Заменить мой план этой копией', exact: true }).click()
  await expect(page.getByText('Копия плана по ссылке')).toHaveCount(0)
  await expect(page.locator('.plan-day-tab.active')).toContainText('День 2')
  await expect(page.locator('.plan-stop:visible')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.plan-day-tab.active')).toContainText('День 2')
})

test('uploads, edits, exports and restores our photos', async ({ page }) => {
  await page.goto('/#/dubai/photos?place=dubai-dubai-mall')
  await page.getByText('Добавить наши фотографии', { exact: true }).click()
  await page
    .getByLabel('Наши фотографии', { exact: true })
    .setInputFiles('public/images/mall-640.webp')
  await page.getByLabel('Подпись', { exact: true }).fill('Мы в Dubai Mall')
  await page.getByLabel('Кто на фото').fill('Илья, семья')
  await page.getByRole('button', { name: 'Сохранить фото', exact: true }).click()
  await expect(page.locator('.album-card')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.album-card')).toContainText('Мы в Dubai Mall')
  await page.getByRole('combobox', { name: 'Какие фото', exact: true }).selectOption('individual')
  await expect(page.locator('.album-card')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Какие фото', exact: true }).selectOption('group')
  await expect(page.locator('.album-card')).toHaveCount(1)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: /Скачать копию/ }).click()
  const backup = await (await download).path()
  await page.getByRole('button', { name: 'Удалить', exact: true }).click()
  await page.getByRole('button', { name: 'Да, удалить', exact: true }).click()
  await expect(page.locator('.album-card')).toHaveCount(0)
  await page.getByLabel('Загрузить копию альбома').setInputFiles(backup!)
  await expect(page.locator('.album-card')).toHaveCount(1)
  await page.getByRole('button', { name: /Изменить фото/ }).click()
  await page.getByLabel('Подпись', { exact: true }).fill('Семья в молле')
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await expect(page.locator('.album-card')).toContainText('Семья в молле')
  await page.getByRole('button', { name: /Открыть наше фото/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})

test('opens licensed gallery and closes it with Escape', async ({ page }) => {
  await page.goto('/#/dubai/place/dubai-frame')
  await expect(page.locator('.gallery-grid figure')).toHaveCount(3)
  await page.getByRole('button', { name: 'Открыть фото: Смотровая внутри Dubai Frame' }).click()
  await expect(page.getByRole('dialog')).toContainText('2 / 3')
  await page.getByRole('button', { name: 'Следующее фото' }).click()
  await expect(page.getByRole('dialog')).toContainText('3 / 3')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
})
