import type { Seed } from './dubai'

export const extraPlaces: Seed[] = [
  {
    id: 'souk-al-bahar',
    name: 'Souk Al Bahar',
    nameRu: 'Сук Аль-Бахар',
    area: 'downtown',
    coordinates: [25.1936, 55.2751],
    category: 'walk',
    image: 'souk-al-bahar',
    short: 'Арабские арки, мост через озеро и другой ракурс фонтанов.',
    description:
      'Зайдём пешком из Dubai Mall через мост: каналы здесь не нужны, главный вид — на Burj Lake и башню. Внутри есть магазины и рестораны, снаружи — набережная для прогулки и фото. Хорошее дополнение к дню в молле без ещё одной поездки на такси. Еда и покупки оплачиваются отдельно.',
    source: 'souk-al-bahar',
    free: true,
    minutes: [45, 90],
    tags: ['free', 'photos', 'evening'],
    best: 'Ближе к закату и перед фонтанами; во время шоу мост может быть людным.',
    transport:
      'Из Dubai Mall пешком через Burj Lake. Прогулочная точка приблизительная; к ресторану строим маршрут отдельно.',
    hours:
      'Магазины и рестораны работают по своим расписаниям. Для вечерней прогулки сверим доступ к мосту и набережной.',
    priceNote: 'Прогулка без входного билета; ресторан и покупки по желанию.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'aya-universe',
    name: 'AYA Universe',
    nameRu: 'AYA — мир света',
    area: 'wafi',
    coordinates: [25.2296, 55.3179],
    category: 'experience',
    image: 'aya-official',
    short: 'Двенадцать залов со светом, зеркалами и необычными инсталляциями.',
    description:
      'Вариант в помещении для смены впечатлений после прогулок. Идём через главный атриум WAFI City на Level One. Внутри яркий свет, громкая музыка и тёмные пространства: при чувствительности к таким эффектам лучше выбрать другое место. Оператор оценивает посещение в 60–90 минут. Залы проходим в своём темпе, не торопясь между световыми сценами.',
    source: 'aya',
    extraSources: ['aya-location', 'review-aya'],
    website: 'https://feverup.com/m/656224',
    amount: 135,
    minutes: [60, 90],
    tags: ['indoors', 'kids', 'photos'],
    priceNote:
      'Обычный вход 135 AED. Family Pass стоит 399 AED за четырёх гостей, если доступен на выбранную дату; в базовом бюджете считаем обычные билеты, пока пакет не подтверждён.',
    variants: [
      { label: 'Обычный билет · 1 гость', type: 'standard', amount: 135 },
      { label: 'Family Pass · 4 гостя · при наличии', type: 'combination', amount: 399 },
    ],
    childPrices: [
      { minAge: 0, maxAge: 2, amount: 0 },
      { minAge: 4, maxAge: 17, amount: 135 },
    ],
    hours:
      'Вс–чт 10:00–22:00, пт–сб 10:00–00:00. Последний вход за час до закрытия. Наш маршрут рассчитывается до 22:00.',
    schedule: { opens: '10:00', closes: '22:00' },
    booking: true,
    best: 'У открытия или в дневную жару, если удобен этот район.',
    transport:
      'WAFI City, Oud Metha. Зелёная ветка до Dubai Healthcare City, около шести минут пешком по данным оператора. Из JA сравним с прямым Hala Max.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'crocodile-park',
    name: 'Dubai Crocodile Park',
    nameRu: 'Парк крокодилов',
    area: 'mushrif',
    coordinates: [25.2026, 55.4412],
    category: 'nature',
    image: 'crocodile-official',
    short: 'Крокодилы, подводный обзор и небольшой музей — для отдельного выезда.',
    description:
      'Парк у Mushrif с открытыми вольерами, аквариумом и музеем естественной истории. Это дальняя поездка из JA: выбираем её ради интереса к животным, а не добавляем к Downtown между делом. Оператор указывает знакомство с маленькими крокодилами в 11:30 и 16:30; проведение и условия участия уточняем на месте. На обычную прогулку закладываем около двух часов без дороги.',
    source: 'crocodile',
    extraSources: ['crocodile-visit', 'crocodile-ages'],
    amount: 95,
    childPrices: [
      { minAge: 0, maxAge: 2, amount: 0 },
      { minAge: 3, maxAge: 11, amount: 75 },
    ],
    priceNote:
      'Взрослый 95 AED, детский 75 AED; до трёх лет бесплатно. Для ребёнка 11 лет считаем детский билет. Возрастную границу сверяем при покупке.',
    minutes: [90, 150],
    tags: ['kids', 'animals', 'outdoors'],
    booking: true,
    hours: 'Ежедневно 10:00–20:00.',
    schedule: { opens: '10:00', closes: '20:00' },
    best: 'Утром или ближе к 16:30; часть маршрута проходит на улице.',
    transport:
      'Tripoli Street, Mushrif. Метка по карте оператора; для шести человек сравниваем прямой Hala Max с долгой пересадочной поездкой.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'miracle-garden',
    name: 'Dubai Miracle Garden',
    nameRu: 'Сад цветов Miracle Garden',
    area: 'gardens',
    coordinates: [25.0609, 55.2447],
    category: 'nature',
    image: 'miracle',
    short: 'Цветочные арки, огромный самолёт и прогулка всей компанией.',
    description:
      'Большой сад под открытым небом. Удобно объединить с соседним Butterfly Garden, чтобы не ехать в этот район дважды. На нашу поездку сезонное открытие заявлено с 8 октября: 6–7 октября сюда не ставим. Утром обычно комфортнее гулять и фотографироваться; возьмём воду и защиту от солнца.',
    source: 'miracle-garden',
    website: 'https://www.dubaimiraclegarden.com/tour/1',
    amount: 100,
    priceNote:
      'Объявленный тариф сезона 15: взрослый 100 AED, ребёнок 80 AED; VAT и итоговую сумму смотрите при оформлении. Resident-тариф требует Emirates ID и к нам не относится.',
    minutes: [90, 150],
    tags: ['kids', 'photos', 'outdoors'],
    best: 'Утром 8–10 октября, после подтверждения открытия сезона.',
    transport:
      'Al Barsha South, рядом с Butterfly Garden. Из MOE можно ехать автобусом 105 или такси; для шестерых сравним Hala Max с билетами на автобус.',
    hours: 'В сезон: 09:00–21:00, последний вход за 30 минут до закрытия.',
    schedule: { opens: '09:00', closes: '21:00' },
    opensOn: '2026-10-08',
    booking: true,
    extraSources: ['miracle-season'],
    checkedAt: '2026-10-03',
  },
  {
    id: 'butterfly-garden',
    name: 'Dubai Butterfly Garden',
    nameRu: 'Сад бабочек Butterfly Garden',
    area: 'gardens',
    coordinates: [25.0633, 55.2454],
    category: 'nature',
    image: 'butterfly',
    short: 'Бабочки рядом с нами в прохладных крытых куполах.',
    description:
      'Крытый сад возле Miracle Garden: можно рассматривать бабочек вблизи и узнать, как они развиваются. Сам Butterfly Garden работает круглый год, поэтому его не нужно привязывать к открытию цветочного сада. Крылья не трогаем и смотрим под ноги. Для ребёнка 11 лет отдельная скидка не заявлена: в бюджете общий тариф.',
    source: 'butterfly-garden',
    website: 'https://www.dubaimiraclegarden.com/butterfly-garden',
    amount: 50,
    priceNote:
      'General Admission на официальной странице — от 50 AED; до 3 лет бесплатно с документом. Комбо с Miracle Garden выбирается отдельно.',
    minutes: [90, 150],
    tags: ['kids', 'photos', 'indoors'],
    best: 'До 18:00; сначала бабочки, затем цветочный сад или MOE.',
    transport: 'Al Barsha South, непосредственно рядом с Miracle Garden.',
    hours: 'Круглый год, ежедневно 09:00–18:00. Последний вход за 30 минут до закрытия.',
    schedule: { opens: '09:00', closes: '18:00' },
    childPrices: [
      { minAge: 0, maxAge: 2, amount: 0 },
      { minAge: 3, maxAge: 17, amount: 50 },
    ],
    booking: true,
    checkedAt: '2026-10-03',
  },
  {
    id: 'mall-of-the-emirates',
    name: 'Mall of the Emirates · MOE',
    nameRu: 'Mall of the Emirates — MOE',
    area: 'al-barsha',
    coordinates: [25.1182, 55.2006],
    category: 'shopping',
    image: 'moe',
    short: 'Магазины, рестораны и настоящий снег в Ski Dubai.',
    description:
      'Большой торговый центр с магазинами, супермаркетом, кинотеатром и Ski Dubai. Можно разделиться по интересам и договориться о встрече на обед. Хорошая прохладная остановка после садов Miracle и Butterfly. Покупки и снежные активности считаем отдельно от бесплатного входа.',
    source: 'mall-of-the-emirates',
    website: 'https://www.malloftheemirates.com/en',
    free: true,
    minutes: [120, 240],
    tags: ['kids', 'indoors', 'shopping', 'free'],
    best: 'Днём или после прогулки по садам; магазины смотрим по списку, чтобы не ходить весь день.',
    transport:
      'Красная линия метро, станция Mall of the Emirates; переход в торговый центр. От садов — отдельный участок на такси или автобусе.',
    hours:
      'Часы магазинов и отдельных развлечений смотрим в разделе Plan your visit; праздничные дни могут отличаться.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'dubai-outlet-mall',
    name: 'Dubai Outlet Mall',
    nameRu: 'Dubai Outlet Mall',
    area: 'dubailand',
    coordinates: [25.072, 55.4005],
    category: 'shopping',
    image: 'mall',
    imageNote: 'На фото Dubai Mall, не Dubai Outlet Mall. Снимок самого аутлета пока не добавлен.',
    short: 'Аутлет для покупок: лучше ехать с конкретным списком.',
    description:
      'Отдельный торговый центр на Dubai–Al Ain Road. Скидка на вывеске не всегда означает выгодную покупку: сравним нужные вещи и размеры заранее. От нашего отеля это заметный выезд, поэтому не стоит ехать ради одного случайного магазина. Не путать с The Outlet Village рядом с Dubai Parks.',
    source: 'dubai-outlet-mall',
    website: 'https://dubaioutletmall.com/faq/',
    free: true,
    minutes: [120, 240],
    tags: ['indoors', 'shopping', 'free'],
    best: 'В день, когда действительно хотим заняться покупками.',
    transport:
      'Dubai–Al Ain Road, Route 66. Метро к самому моллу нет; проверим Hala Max туда и обратно.',
    hours: 'Вс–чт 10:00–22:00; пт–сб 10:00–00:00. События и магазины могут иметь отдельные часы.',
    schedule: { opens: '10:00', closes: '22:00' },
    checkedAt: '2026-10-03',
  },
  {
    id: 'outlet-village',
    name: 'The Outlet Village',
    nameRu: 'Аутлет The Outlet Village',
    area: 'jebel-ali',
    coordinates: [24.9164, 55.0037],
    category: 'shopping',
    image: 'riverland',
    imageNote: 'На фото соседний Riverland, не The Outlet Village.',
    short: 'Аутлет у Dubai Parks — ближе к нашему отелю.',
    description:
      'Крытые торговые улицы в стиле итальянского городка возле Dubai Parks. Можно зайти после Motiongate или LEGOLAND, если останутся силы. Для нашего отеля это более близкий вариант, чем Dubai Outlet Mall; набор магазинов у них разный. Сначала посмотрим бренды на сайте, потом решим, стоит ли ехать.',
    source: 'outlet-village',
    website: 'https://theoutletvillage.ae/',
    free: true,
    minutes: [90, 180],
    tags: ['indoors', 'shopping', 'free'],
    best: 'Вместе с Dubai Parks или в отдельный короткий выезд из отеля.',
    transport: 'Jebel Ali, рядом с Dubai Parks and Resorts; отель может предложить трансфер.',
    hours: 'Актуальные часы смотрим в Plan your visit на сайте молла.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'ibn-battuta-mall',
    name: 'Ibn Battuta Mall',
    nameRu: 'Торговый центр Ibn Battuta',
    area: 'ibn-battuta',
    coordinates: [25.0443, 55.1206],
    category: 'shopping',
    image: 'ibn-battuta',
    short: 'Тематические дворы и магазины по пути от нашего отеля.',
    description:
      'Торговый центр с залами, оформленными по странам путешествий Ибн Баттуты. Есть смысл заглянуть в Персидский двор и совместить это с покупками или обедом. Рядом метро Ibn Battuta: можно попробовать связку Hala Max от отеля и поезд дальше в город, сравнив её с прямым такси на всю шестёрку.',
    source: 'ibn-battuta-mall',
    website: 'https://www.ibnbattutamall.com/',
    free: true,
    minutes: [90, 180],
    tags: ['indoors', 'shopping', 'kids', 'free'],
    best: 'Для обеда и покупок по пути; не обязательно посвящать весь день.',
    transport: 'Красная линия метро, Ibn Battuta; от JA нужен отдельный участок дороги.',
    hours: 'Часы торгового центра и отдельных заведений смотрим на официальном сайте.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'dubai-marina-mall',
    name: 'Dubai Marina Mall',
    nameRu: 'Dubai Marina Mall',
    area: 'marina',
    coordinates: [25.0764, 55.1405],
    category: 'shopping',
    image: 'marina-mall',
    short: 'Небольшая остановка за покупками перед прогулкой по Marina.',
    description:
      'Более компактный молл прямо у набережной Marina. Удобно встретиться здесь, поесть или переждать жару, а вечером выйти к воде. Вместо отдельного выезда из отеля объединим молл, Marina и JBR в один день. За скидками специально сюда ехать необязательно.',
    source: 'dubai-marina-mall',
    website: 'https://www.dubaimarinamall.com/',
    free: true,
    minutes: [60, 120],
    tags: ['shopping', 'indoors', 'evening', 'free'],
    best: 'Перед вечерней прогулкой по набережной.',
    transport: 'Рядом Dubai Marina и станция DMCC; переходы до трамвая и метро проверим на карте.',
    hours: 'Расписание магазинов и ресторанов — на официальной странице молла.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'dubai-festival-city-mall',
    name: 'Dubai Festival City Mall',
    nameRu: 'Dubai Festival City Mall',
    area: 'festival-city',
    coordinates: [25.2218, 55.3516],
    category: 'shopping',
    image: 'festival-mall',
    short: 'Магазины и вечерняя прогулка у Festival Bay.',
    description:
      'Торговый центр на другой стороне Creek. Здесь можно совместить покупки, ужин и шоу IMAGINE у воды, если оно проходит в выбранный вечер. От JA далеко: лучше объединить с другими местами этой части города, а не возвращаться сюда отдельным такси. Расписание шоу смотрим перед выездом.',
    source: 'dubai-festival-city-mall',
    website: 'https://www.dubaifestivalcitymall.com/',
    free: true,
    minutes: [120, 210],
    tags: ['shopping', 'indoors', 'kids', 'evening', 'free'],
    best: 'Ближе к вечеру, если хотим остаться у Festival Bay.',
    transport:
      'Dubai Festival City; прямой станции метро у молла нет, последний участок обычно требует другого транспорта.',
    hours: 'Часы магазинов и шоу IMAGINE проверим отдельно на сайте молла.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'dubai-hills-mall',
    name: 'Dubai Hills Mall',
    nameRu: 'Dubai Hills Mall',
    area: 'dubai-hills',
    coordinates: [25.0984, 55.2388],
    category: 'shopping',
    image: 'hills-mall',
    short: 'Покупки, рестораны и развлечения в Dubai Hills.',
    description:
      'Современный торговый центр с магазинами и развлечениями, в том числе The Storm Coaster. Выбираем его, если интересны конкретные бренды или аттракционы; поездку ради ещё одного молла можно пропустить. Горка оплачивается отдельно, а ограничения по росту и здоровью смотрим у оператора.',
    source: 'dubai-hills-mall',
    website: 'https://www.dubaihillsmall.ae/',
    free: true,
    minutes: [120, 210],
    tags: ['shopping', 'indoors', 'kids', 'free'],
    best: 'Днём, если хотим сделать паузу от прогулок на солнце.',
    transport: 'Dubai Hills Estate, Al Khail Road; на метро прямо к входу не доехать.',
    hours: 'Часы торгового центра и аттракционов смотрим отдельно на официальном сайте.',
    checkedAt: '2026-10-03',
  },
  {
    id: 'ski-dubai',
    name: 'Ski Dubai',
    nameRu: 'Снежный парк Ski Dubai',
    area: 'al-barsha',
    coordinates: [25.1172, 55.1998],
    category: 'experience',
    image: 'ski',
    short: 'Снег посреди октября — прямо внутри MOE.',
    description:
      'Крытый снежный парк и лыжный склон внутри Mall of the Emirates. Для нашей компании ориентир — Snow Daycation: снежный парк, подъёмник, обед и одна активность на выбор. Катание на склоне — отдельный продукт для опытных лыжников. Ребёнку 11 лет нужен сопровождающий взрослый с билетом; ограничения отдельных активностей проверим до покупки.',
    source: 'ski-dubai',
    website: 'https://www.skidxb.com/en-ae/ski-dubai/passes-packages/explore',
    amount: 335,
    priceNote:
      'Snow Daycation — 335 AED на человека: снежный парк, подъёмник, обед, шкафчик, перчатки и одна активность на выбор. Двухчасовой склон за 240 AED — другой продукт, для опытных лыжников.',
    minutes: [120, 210],
    tags: ['indoors', 'kids', 'extreme'],
    best: 'Отдельный сеанс в день посещения Mall of the Emirates.',
    transport: 'Внутри Mall of the Emirates, красная линия метро.',
    hours:
      'Пн–чт 10:00–23:00; пт 10:00–00:00; сб–вс 09:00–00:00. Последний билет за 90 минут до закрытия. В расчёте используем общее окно 10:00–23:00.',
    schedule: { opens: '10:00', closes: '23:00' },
    booking: true,
    checkedAt: '2026-10-03',
  },
  {
    id: 'global-village',
    name: 'Global Village',
    nameRu: 'Global Village — на следующую поездку',
    area: 'dubailand',
    coordinates: [25.0703, 55.3085],
    category: 'theme-park',
    image: 'hero',
    imageNote: 'На фото панорама Дубая; фотографию Global Village пока не добавили.',
    short: 'Ярмарка стран и вечерние развлечения — открытие после наших дат.',
    description:
      'Большой вечерний парк с павильонами стран, едой и аттракционами. Сезон 31 открывается 14 октября 2026 — после нашего отъезда 11 октября. Сохраним идею на будущее, но в маршрут 6–10 октября её не включаем.',
    source: 'global-village',
    website: 'https://www.globalvillage.ae/en/node/64675',
    minutes: [180, 300],
    tags: ['kids', 'evening', 'shopping'],
    best: 'Вечером после открытия нового сезона.',
    transport: 'Dubailand; выезд обычно требует такси или автобуса.',
    hours:
      'Сезон открывается 14 октября 2026; часы и билеты нового сезона смотрим после объявления.',
    opensOn: '2026-10-14',
    booking: true,
    checkedAt: '2026-10-03',
  },
]
export const extraAreas: [string, string, string, string, number, number][] = [
  [
    'wafi',
    'WAFI · Oud Metha',
    'WAFI и Уд-Мета',
    'AYA и WAFI City возле зелёной ветки метро.',
    25.2296,
    55.3179,
  ],
  [
    'mushrif',
    'Mushrif',
    'Мушриф',
    'Парк крокодилов; отдельный дальний выезд из JA.',
    25.2026,
    55.4412,
  ],
  [
    'gardens',
    'Al Barsha South · Gardens',
    'Сады в Al Barsha South',
    'Miracle Garden и Butterfly Garden рядом друг с другом.',
    25.062,
    55.245,
  ],
  [
    'al-barsha',
    'Al Barsha · MOE',
    'Аль-Барша и MOE',
    'Mall of the Emirates и Ski Dubai.',
    25.118,
    55.2,
  ],
  [
    'ibn-battuta',
    'Ibn Battuta',
    'Ibn Battuta',
    'Торговый центр и метро по пути из JA.',
    25.044,
    55.12,
  ],
  [
    'dubailand',
    'Dubailand',
    'Дубайленд',
    'Dubai Outlet Mall и сезонные парки; проверяем расстояния.',
    25.07,
    55.4,
  ],
  [
    'festival-city',
    'Festival City',
    'Festival City',
    'Торговый центр и Festival Bay у Creek.',
    25.222,
    55.351,
  ],
  [
    'dubai-hills',
    'Dubai Hills',
    'Dubai Hills',
    'Торговый центр в Dubai Hills Estate.',
    25.098,
    55.239,
  ],
]
