export const ticketLinks: ReadonlyArray<
  readonly [string, string, string, string, number?, string?]
> = [
  [
    'aya-universe',
    'trip-com',
    'https://ru.trip.com/things-to-do/detail/102771585/',
    'На 6 октября: вход без трансфера, с 3 лет один тариф. Без возврата и изменения даты. Это текущий пакет, старое предложение со скидкой уже перенаправляет в каталог.',
    3802.54,
    'RUB',
  ],
  [
    'the-view-at-the-palm',
    'trip-com',
    'https://ru.trip.com/things-to-do/detail/103874472/',
    'На 6 октября: обычный вход на 52 этаж, 10:00–15:30. Дети 3–12 лет — 1 572 ₽. Закат, VIP и Next Level — другие пакеты. Без возврата и изменения даты.',
    2297.53,
    'RUB',
  ],
  [
    'aquaventure',
    'trip-com',
    'https://ru.trip.com/things-to-do/detail/102796383/',
    'На 6 октября: аквапарк без аквариума, тариф с 3 лет. Встреча в Atlantis в 10:00 — из JA нужно выехать раньше обычного. Ваучер отправляют через WhatsApp. Без возврата и изменения даты; условия хранения вещей проверьте у продавца.',
    5029.15,
    'RUB',
  ],
  [
    'dubai-frame',
    'trip-com',
    'https://www.trip.com/travel-guide/attraction/dubai/dubai-frame-46832162?curr=AED&locale=en-XX',
    'Страница самой Рамки с предложениями. Сравните вход без трансфера и детский тариф: цену конкретного пакета на дату поездки пока не фиксируем.',
  ],
  [
    'miracle-garden',
    'trip-com',
    'https://ru.trip.com/travel-guide/attraction/dubai/dubai-miracle-garden-15053335?curr=RUB&locale=ru-RU&poiType=3&scene=ticket',
    'Страница самого сада. На 3 октября сезон ещё не открыт и отдельный входной билет не показан; цены экскурсий не сравниваем с обычным входом. Наличие на 8–10 октября проверяйте после открытия продаж.',
  ],
  [
    'butterfly-garden',
    'trip-com',
    'https://www.trip.com/travel-guide/attraction/dubai/dubai-butterfly-garden-33067608',
    'Страница самого Butterfly Garden. Выбирайте входной билет; экскурсии с трансфером и пакеты с Miracle Garden сравнивайте отдельно. Цена на дату поездки пока не подтверждена.',
  ],
  [
    'burj-khalifa',
    'klook',
    'https://www.klook.com/en-US/activity/2228-burj-khalifa-observation-deck-dubai/',
    'Уровни 124/125; fast track и 148 этаж — отдельные варианты.',
  ],
  [
    'burj-khalifa',
    'tiqets',
    'https://www.tiqets.com/en/dubai-attractions-c60005/tickets-for-burj-khalifa-at-the-top-level-124-125-ticket-p1111392/',
    'Уровни 124/125; пакет и возможность возврата выбираются при оформлении.',
  ],
  [
    'burj-khalifa',
    'wegotrip',
    'https://wegotrip.com/dubai-d292223/burj-khalifa-entrance-ticket-p5140/',
    'Вход на уровни 124/125; уточните наличие аудиогида в выбранном пакете.',
  ],
  [
    'burj-khalifa',
    'getyourguide',
    'https://www.getyourguide.com/de-at/dubai-l173/dubai-burj-khalifa-levels-124-125-entry-ticket-options-t49019/',
    'Уровни 124/125 и дополнительные опции. Язык страницы можно изменить у продавца.',
  ],
  [
    'dubai-aquarium',
    'klook',
    'https://www.klook.com/en-US/activity/9648-dubai-aquarium-underwater-zoo-dubai/',
    'Silver, Gold и Platinum отличаются составом; проверьте срок действия.',
  ],
  [
    'dubai-aquarium',
    'tiqets',
    'https://www.tiqets.com/en/dubai-attractions-c60005/tickets-for-dubai-aquarium-underwater-zoo-p974238/',
    'Aquarium & Underwater Zoo; состав пакета выбирается у продавца.',
  ],
  [
    'sky-views',
    'klook',
    'https://www.klook.com/en-US/activity/65926-sky-views-observator-hotel-address-sky-view-ticket/',
    'Обсерватория, горка и Edge Walk — разные варианты посещения.',
  ],
  [
    'dubai-frame',
    'klook',
    'https://www.klook.com/en-GB/activity/30552-dubai-frame-tickets-round-trip-hotel-transfers/',
    'Входной билет; трансфер и дополнительные услуги зависят от варианта.',
  ],
  [
    'dubai-frame',
    'tiqets',
    'https://www.tiqets.com/en/dubai-attractions-c60005/tickets-for-dubai-frame-entry-skydeck-access-p1072266/',
    'Вход в Dubai Frame и доступ на смотровую площадку.',
  ],
  [
    'dubai-frame',
    'sputnik8',
    'https://www.sputnik8.com/ru/dubai/activities/62735-arhitekturnoe-chudo-dubai-frame-vhodnoy-bilet',
    'Входной билет; трансфер не включён.',
  ],
  [
    'dubai-frame',
    'tripster',
    'https://experience.tripster.ru/experience/43111/',
    'Билет на смотровую площадку; проверьте действительность выбранного варианта.',
  ],
  [
    'green-planet',
    'klook',
    'https://www.klook.com/en-US/activity/5798-green-planet-ticket-dubai/',
    'Вход в The Green Planet; дополнительные встречи с животными проверяйте отдельно.',
  ],
  [
    'inside-burj-al-arab',
    'klook',
    'https://www.klook.com/en-US/activity/78925-1-hour-inside-burj-al-arab-join-landmark-tour-dubai/',
    'Групповой тур Inside Burj Al Arab; напитки и другие дополнения зависят от варианта.',
  ],
  [
    'the-view-at-the-palm',
    'klook',
    'https://www.klook.com/en-US/activity/57080-1-day-view-palm-ticket-direct-entry/',
    'Уровень 52; prime/non-prime и Next Level различаются.',
  ],
  [
    'aquaventure',
    'klook',
    'https://www.klook.com/fr/activity/2244-atlantis-aquaventure-water-park-dubai/',
    'Дневной аквапарк и вечерние мероприятия — разные пакеты. Язык можно изменить у продавца.',
  ],
  [
    'lost-world-aquarium',
    'klook',
    'https://www.klook.com/en-US/activity/179992-the-lost-chambers-aquarium-ticket-in-dubai/',
    'Lost World Aquarium; проверьте дату посещения и состав пакета.',
  ],
  [
    'ain-dubai',
    'klook',
    'https://www.klook.com/en-US/activity/60444-ain-dubai-observation-cabins-bluewaters-island/',
    'Смотровая кабина; премиальные и социальные пакеты отличаются.',
  ],
  [
    'motiongate',
    'klook',
    'https://www.klook.com/en-GB/activity/9650-motiongate-dubai-ticket-dubai/',
    'MOTIONGATE Dubai; состав паркового или комбинированного билета уточняйте.',
  ],
  [
    'legoland-dubai',
    'klook',
    'https://www.klook.com/en-US/activity/9651-legoland-dubai-ticket-dubai/',
    'LEGOLAND Dubai; аквапарк не следует считать включённым без проверки пакета.',
  ],
]

export const ticketLinksCheckedAt = '2026-10-03'
